[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fix-comment-length"
dynamic = ["version"]
dependencies = []

[project.scripts]
fcl = "fixcommentlength:main"

[tool.setuptools.dynamic]
version = {attr = "fixcommentlength.__version__"}
